# Generated by rust2rpm 26
%bcond_without check

# prevent library files from being installed
%global cargo_install_lib 0

Name:           userborn
Version:        main
Release:        %autorelease
Summary:        Declaratively bear (manage) Linux users and groups

License:        MIT
URL:            https://github.com/nikstur/userborn
Source:         https://github.com/nikstur/userborn/archive/%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 26 mkpasswd
Requires:       mkpasswd

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -p1
%cargo_prep

# the checksums in the lock file might not match
rm rust/userborn/Cargo.lock

%generate_buildrequires
cd rust/userborn
%cargo_generate_buildrequires

%build
cd rust/userborn
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
cd rust/userborn
%cargo_install

%if %{with check}
%check
cd rust/userborn
%cargo_test
%endif

%files
%license LICENSE
%license rust/userborn/LICENSE.dependencies
%{_bindir}/userborn

%changelog
%autochangelog
